a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Há espaço? ', a.isspace())
print('É um numérico? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em Maiscula?', a.isupper())
print('Está em minuscula? ', a.islower())
print('Está Capitalizada? ', a.istitle())
